import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * Turns data/master/design-tokens.json into CSS custom properties.
 *
 * The stylesheet never writes a colour, radius or duration of its own: it maps
 * its semantic names onto the tokens generated here, so the palette has one
 * source and a token change reaches every screen at once.
 */
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const tokensPath = path.join(root, 'data/master/design-tokens.json');
const outputPath = path.join(root, 'src/styles.tokens.css');

const kebab = (value) => value.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();

function flatten(prefix, value, lines) {
  for (const [key, entry] of Object.entries(value)) {
    const name = `${prefix}-${kebab(key)}`;
    if (entry !== null && typeof entry === 'object' && !Array.isArray(entry)) {
      flatten(name, entry, lines);
    } else if (typeof entry === 'string' || typeof entry === 'number') {
      lines.push(`  ${name}: ${entry};`);
    }
  }
}

export function buildTokenCss(tokens) {
  const lines = [];
  for (const group of ['color', 'categoryColor', 'typography', 'spacing', 'radius', 'shadow', 'motion', 'layout', 'control', 'zIndex']) {
    if (!tokens[group]) continue;
    lines.push(`  /* ${group} */`);
    flatten(`--t-${kebab(group)}`, tokens[group], lines);
  }
  return [
    '/*',
    ` * Generated by scripts/build-tokens.mjs from data/master/design-tokens.json`,
    ` * (${tokens.designConcept}). Do not edit by hand.`,
    ' */',
    ':root {',
    ...lines,
    '}',
    ''
  ].join('\n');
}

const tokens = JSON.parse(fs.readFileSync(tokensPath, 'utf8'));
const css = buildTokenCss(tokens);
const previous = fs.existsSync(outputPath) ? fs.readFileSync(outputPath, 'utf8') : '';
if (previous !== css) fs.writeFileSync(outputPath, css);
console.log(`Design tokens written: ${css.split('\n').length - 7} custom properties from ${tokens.designConcept}.`);
